# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'color_change.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(495, 284)
        MainWindow.setMinimumSize(QtCore.QSize(495, 284))
        MainWindow.setMaximumSize(QtCore.QSize(495, 284))
        MainWindow.setStyleSheet("background-color:rgb(224, 232, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 140, 71, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(0, 0, 127);\n"
"color:white;\n"
"border-radius:22px;}\n"
"\n"
"QPushButton::hover{\n"
"background-color:rgb(172, 45, 155);\n"
"color:rgb(255, 255, 0);\n"
"border-radius:22px;}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.button)

###################################################################################################################
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 50, 348, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
##################################################################################################################
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)

####################################################################################################################
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)

##########################################################################################################################
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout.addWidget(self.radioButton_4)

#############################################################################################################################
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

################################################################################################################

    def button(self):
        if self.radioButton.isChecked()==True:
            print("Souvik")
            MainWindow.setStyleSheet("background-color:red;")
        elif self.radioButton_2.isChecked()==True:
            print("Anu1")
            MainWindow.setStyleSheet("background-color:blue;")
        elif self.radioButton_3.isChecked()==True:
            print("Anu2")
            MainWindow.setStyleSheet("background-color:yellow;")
        else:
            print("Anu3")
            MainWindow.setStyleSheet("background-color:green;")






#########################################################################################################3

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Go"))
        self.radioButton.setText(_translate("MainWindow", "Red"))
        self.radioButton_2.setText(_translate("MainWindow", "Blue"))
        self.radioButton_3.setText(_translate("MainWindow", "Yellow"))
        self.radioButton_4.setText(_translate("MainWindow", "Green"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
