# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'food_house.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 532)
        MainWindow.setStyleSheet("background-color:rgb(8, 82, 200);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 20, 311, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_3.setMouseTracking(False)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")



###########################################################################################################
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 90, 169, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_5.setStyleSheet("color:rgb(255, 255, 255);")
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout.addWidget(self.checkBox_5)


###############################################################################################################3
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_4.setStyleSheet("color:rgb(255, 255, 255);")
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)


#############################################################################################33
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_2.setStyleSheet("color:rgb(255, 255, 255);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)


############################################################################################################
        self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_6.setStyleSheet("color:rgb(255, 255, 255);")
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout.addWidget(self.checkBox_6)


#################################################################################################################
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setStyleSheet("color:rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)


#############################################################################################################
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(120, 230, 171, 83))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")


##########################################################################################################
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_3.setStyleSheet("color:rgb(255, 255, 255);")
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)


#####################################################################################################
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_7.setStyleSheet("color:rgb(255, 255, 255);")
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_2.addWidget(self.checkBox_7)


#################################################################################################
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_8.setStyleSheet("color:rgb(255, 255, 255);")
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout_2.addWidget(self.checkBox_8)


###########################################################################################################
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(70, 400, 285, 26))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget2)

##########################################################################################################
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)


###########################################################################################################
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(70, 360, 238, 22))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget3)


###############################################################################################################
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setStyleSheet("\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton.clicked.connect(self.button)


###################################################################################################################
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("color:rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)

#################################################################################################################
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(72, 440, 152, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setStyleSheet("\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton.clicked.connect(self.button2)


################################################################################################################
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(230, 440, 78, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("color:rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")


###############################################################################################################
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

###################################################################################################################
    def button(self):
        
        a=0
        b=0
        c=0
        d=0
        e=0
        f=0
        g=0
        h=0
        tot=0
        test1=int(self.checkBox_5.checkState())
        test2=int(self.checkBox_4.checkState())
        test3=int(self.checkBox_2.checkState())
        test4=int(self.checkBox_6.checkState())
        test5=int(self.checkBox.checkState())
        test6=int(self.checkBox_3.checkState())
        test7=int(self.checkBox_7.checkState())
        test8=int(self.checkBox_8.checkState())
        if test1==2:
            print("1st ")
            a=150
        if test2==2:
            print("2nd ")
            b=120

        if test3==2:
            print("3nd ")
            c=80

        if test4==2:
            print("4th ")
            d=60
        if test5==2:
            print("5th ")
            e=100
        if test6==2:
            print("6th ")
            f=60
        if test7==2:
            print("7th ")
            g=50
        if test8==2:
            print("8th ")
            h=55

        tot=str(a+b+c+d+e+f+g+h)
        print("Total", tot)

        self.lineEdit_3.setText(tot)

    ########################################################################3
    def button2(self):

        a=0
        b=0
        c=0
        d=0
        e=0
        f=0
        g=0
        h=0
        tot=0
        disc=0

        test1=int(self.checkBox_5.checkState())
        test2=int(self.checkBox_4.checkState())
        test3=int(self.checkBox_2.checkState())
        test4=int(self.checkBox_6.checkState())
        test5=int(self.checkBox.checkState())
        test6=int(self.checkBox_3.checkState())
        test7=int(self.checkBox_7.checkState())
        test8=int(self.checkBox_8.checkState())
        if test1==2:
            print("1st ")
            a=150
        if test2==2:
            print("2nd ")
            b=120

        if test3==2:
            print("3nd ")
            c=80

        if test4==2:
            print("4th ")
            d=60
        if test5==2:
            print("5th ")
            e=100
        if test6==2:
            print("6th ")
            f=60
        if test7==2:
            print("7th ")
            g=50
        if test8==2:
            print("8th ")
            h=55

        d1=a+b+c+d+e+f+g+h
        disc=str(a+b+c+d+e+f+g+h)
        d2=d1*10/100
        disc2=str(d1*10/100)
        d3=str(d1-d2)

        self.lineEdit_4.setText(d3)


################################################################################################################
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Welcome To The Food House"))
        self.checkBox_5.setText(_translate("MainWindow", "Pizza  Rs. 150"))
        self.checkBox_4.setText(_translate("MainWindow", "Burger  Rs. 120"))
        self.checkBox_2.setText(_translate("MainWindow", "Vada Pav  Rs. 80"))
        self.checkBox_6.setText(_translate("MainWindow", "Sandwitch  Rs. 60"))
        self.checkBox.setText(_translate("MainWindow", "Dhosa  Rs. 100"))
        self.checkBox_3.setText(_translate("MainWindow", "Itli  Rs. 60"))
        self.checkBox_7.setText(_translate("MainWindow", "Role  Rs. 50"))
        self.checkBox_8.setText(_translate("MainWindow", "Chowming  Rs. 55"))
        self.label.setText(_translate("MainWindow", "Discount 10%"))
        self.pushButton.setText(_translate("MainWindow", "  Grand Total         "))
        self.pushButton_2.setText(_translate("MainWindow", "Total Bill"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
