# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(432, 334)
        MainWindow.setStyleSheet("background-color:rgb(0, 0, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(230, 40, 181, 31))
        self.lineEdit.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color:rgb(0, 0, 0);\n"
" border-radius:10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 110, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(240, 240, 240);\n"
"color:rgb(0, 0, 0);\n"
" border-radius:10px;}\n"
"\n"
"QPushButton::hover{\n"
"background-color:rgb(0, 255, 255);\n"
"color:rgb(255, 255, 0);\n"
" border-radius:10px;}")
        self.pushButton.setObjectName("pushButton")
        ################################################################################
        self.pushButton.clicked.connect(self.button)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 180, 241, 31))
        self.label_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color:rgb(0, 0, 0);\n"
" border-radius:10px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
    
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        ###############################################################3

        
    def button(self):
        
        a=self.lineEdit.text()
        print("hello", a)
        self.label_2.setText("hello " + a)
 




    ################################################################
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ENTER YOUR NAME"))
        self.pushButton.setText(_translate("MainWindow", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
