# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paasword.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(382, 386)
        MainWindow.setStyleSheet("background-color:rgb(0, 0, 49);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(37, 71, 120, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")


##############################################################################################################
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(163, 71, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color:rgb(255, 255, 255);")
        self.lineEdit.setStyleSheet("border: 2px solid white; border-radius: 10px;")       
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setPlaceholderText("Enter Your User Name")


#############################################################################################################
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(166, 120, 181, 20))
        self.lineEdit_2.setStyleSheet("color:rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setPlaceholderText("Enter Your Password")
        self.lineEdit_2.setStyleSheet("border: 2px solid gray; border-radius: 10px;")
       
#############################################################################
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 120, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        # self.label_2.setEchoMode(QtWidgets.QLineEdit.label_2)

###############################################################################
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 220, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"\n"
"background-color:rgb(242, 246, 255);\n"
"color:rgb(0, 0, 0);\n"
"border-radius:10px;}\n"
"\n"
"\n"
"QPushButton::hover{\n"
"\n"
"background-color:rgb(0, 106, 106);\n"
"color:rgb(255, 255, 255);\n"
"border-radius:10px;}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.button)
################################################################################################################
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 300, 141, 19))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255);\n"
"")
        self.label_3.setObjectName("label_3")

######################################################################################################################
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 300, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 246, 255);\n"
"color:rgb(0, 0, 0);}\n"
"\n"
"QPushButton::hover{\n"
"background-color:rgb(0, 255, 255);\n"
"color:rgb(0, 0, 0);}")
        self.pushButton_2.setObjectName("pushButton_2")

################################################################################################################
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 260, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 246, 255);\n"
"color:rgb(0, 0, 0);}\n"
"\n"
"QPushButton::hover{\n"
"background-color:rgb(132, 198, 198);\n"
"color:rgb(0, 0, 0);}")
        self.pushButton_3.setObjectName("pushButton_3")

################################################################################################################
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

####################################################################################################################
    def button(self):
        a=self.lineEdit.text()
        print("User Name : " +a)
        b=self.lineEdit_2.text()
        print("Password : " +b)





##################################################################################################################

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "User Name :    "))
        self.label_2.setText(_translate("MainWindow", "Password  :     "))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.label_3.setText(_translate("MainWindow", "Don\'t have an account?"))
        self.pushButton_2.setText(_translate("MainWindow", "Create"))
        self.pushButton_3.setText(_translate("MainWindow", "Forget Password ?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
